site_name: My site
site_url: https://mydomain.org/mysite
theme:
  logo: assets/logo.png
  favicon: assets/favicon.ico
  language: en
  name: material   
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  
  features: 
    - navigation.footer
  palette: 
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: indigo

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details

  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:   
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


nav:
  - Home: index.md
  - Physics: Physics/index.md
  - Math: Math/index.md
  - Sci-Fi Short Stories: Sci-Fi/index.md
  - Clarity Hub: Clarity Hub/index.md
  - Beyond School: Beyond School/index.md
  - Philosophy: Philosophy/index.md
  - Pop Science: Pop-Science/index.md
extra:
  social:
    - icon: simple/facebook
      link: https://www.facebook.com/prince.rayhan.961993