site_name: My site
site_url: https://mydomain.org/mysite
theme:
  logo: assets/logo.png
  favicon: assets/favicon.ico
  language: en
  name: material   
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  
  features: 
        - navigation.footer
  palette: 
  # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: indigo

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - admonition
  - pymdownx.details
  - pymdownx.superfences:   
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


# extra informations in footer

extra:
  social:
    - icon: simple/facebook
      link: https://www.facebook.com/prince.rayhan.961993